"""Timing constants (milliseconds unless noted)."""


class Timing:
    """Timing constants."""

    UI_UPDATE_INTERVAL = 50
    AUDIO_LEVEL_UPDATE_INTERVAL = 100
    STATUS_UPDATE_INTERVAL = 200

    MODEL_LOAD_TIMEOUT = 30000
    TRANSCRIPTION_TIMEOUT = 120000
    API_REQUEST_TIMEOUT = 30000

    STARTUP_DELAY = 1000
    SHUTDOWN_DELAY = 2000
    OVERLAY_HIDE_DELAY = 3000

    RETRY_DELAY = 1000
    EXPONENTIAL_BACKOFF_BASE = 2
